# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClearScore-Mini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClearScore-Mini

	pod 'ReachabilitySwift', '~> 5.0'

  target 'ClearScore-MiniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClearScore-MiniUITests' do
    # Pods for testing
  end

end
